### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by JDuggal760** [Ashwin-op/GitHub-Follow-Bot#2]
Hi! Great idea. For some reason it doesn't work, do I have to run it on my computer locally
I was using google colab and this was one issue I kept running into. I inputted my username and my password as well

![image](https://user-images.githubusercontent.com/77640905/113369192-ae7ae380-932e-11eb-84c5-fc7cc4426026.png)

**Comment by Ashwin-op** [comment]
Hi @JDuggal760 !

You actually have to run it like `!python3 GitHub-Follow-Bot/follow_bot.py`. Also, there will be some code changes required if you wish to run in Google Colab (for ex: adding a *--headless* flag, etc...)

**Comment by JDuggal760** [comment]
hmm I tried running it on windows and linux how would I install selenium on linux I’m getting a lot of errors with pip and python

**Comment by Ashwin-op** [comment]
You can install selenium like `pip install selenium`.

What kind of errors are you getting? Can you elaborate?

**Comment by JDuggal760** [comment]
I'm going to retry on  a different device ill see if I still get the same error messages but pip install selenium wasn't working last time

**Comment by JDuggal760** [comment]
Hi 
Not sure if your still there but I installed selenium and chrome driver successfully I'm getting this one error though 
``Traceback (most recent call last):
  File "/root/GitHub-Follow-Bot/follow_bot.py", line 9, in <module>
    driver = webdriver.Chrome()
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)''

Not sure if that means anything I just ran  python3 follow_bot.py

**Comment by Ashwin-op** [comment]
Looks like maybe the chrome driver isn't in the path

**Comment by JDuggal760** [comment]
How would I fix that and put it in the right path?
